export const oblasts = [
  'Cherkasy Oblast',
  'Chernihiv Oblast',
  'Chernivtsi Oblast',
  'Dnipropetrovsk Oblast',
  'Donetsk Oblast',
  'Ivano-Frankivsk Oblast',
  'Kharkiv Oblast',
  'Kherson Oblast',
  'Khmelnytskyi Oblast',
  'Kyiv Oblast',
  'Kirovohrad Oblast',
  'Luhansk Oblast',
  'Lviv Oblast',
  'Mykolaiv Oblast',
  'Odessa Oblast',
  'Poltava Oblast',
  'Rivne Oblast',
  'Sumy Oblast',
  'Ternopil Oblast',
  'Vinnytsia Oblast',
  'Volyn Oblast',
  'Zakarpattia Oblast',
  'Zaporizhzhia Oblast',
  'Zhytomyr Oblast'
]

export const typesOfIncident = [
  '1 Unlawful attacks on civilians',
  '1.1 Children',
  '2 Attacks on hospitals, medical staff and vehicles',
  '3 Attacks on civilian objects',
  '3.1 Undefined',
  '3.2 Residential',
  '3.2.1 Water supply',
  '3.2.2 Heating',
  '3.3 Industrial',
  '3.4 Cultural',
  '3.5 Memorial',
  '3.6 Administrative',
  '3.7 Commercial',
  '3.8 Warehouse',
  '3.9 Educational institutions',
  '3.9.1 Kidergarten',
  '3.9.2 School',
  '3.9.3 College',
  '3.9.4 University / Institute',
  '3.9.5 Boarding school',
  '3.1 Religious',
  '3.11 Transportation',
  '3.11.1 Automobiles',
  '3.11.2 Railway',
  '3.11.3 Public transportation',
  '3.12 Bridges',
  '3.13 Sport facilities',
  '3.14 Energy',
  '3.14.1 Power plant',
  '3.14.2 Gas',
  '3.14.3 Oil industry',
  '3.14.4 Petrol station',
  '3.14.5 Electrical grid and substations',
  '3.14.6 Service and repair vehicles',
  '3.15 Food industry / agriculture',
  '3.15.1 Agricultural machinery',
  '3.16 Law enforcement and rescue services',
  '3.16.1 Police station',
  '3.16.2 Fire station / Rescue center',
  '3.16.3 Law enforcement and rescue vehicles',
  '3.17 Telecommunications infrastructure',
  '3.18 Humanitarian aid center',
  '4 Murder',
  '5 Torture and inhuman or degrading treatment',
  '6 Enforced disappearances of persons',
  '6.1 Local officials',
  '6.2 Journalists',
  '6.3 Local activists',
  '7 Unlawful confinement ',
  '8 Unlawful attacks on the environment',
  '9 Sexual and gender based violence',
  '10 Pillaging / robbery',
  '10.1 Stolen vehicle',
  '11 Attack on animals',
  '12 Deportation or forcible transfer of population',
  '13 Compelling civilians to take part in the operations of war directed against their own country'
]

export const meansOfAttack = [
  '1 Undefined',
  '2 Artillery fire',
  '2.1 Undefined',
  '2.2 Multiple Launch Rocket System (MLRS)',
  '2.2.1 Incendiary munition',
  '2.2.2 Cluster munition',
  '2.2.3 Thermobaric munition',
  '2.2.4 High-explosive munition',
  '2.2.5 Undefined',
  '2.3 Cannon / Howitzer / Mortar',
  '2.3.1 Incendiary munition',
  '2.3.2 Cluster munition',
  '2.3.3 Thermobaric munition',
  '2.3.4 High-explosive munition',
  '2.3.5 Undefined',
  '3 Air strike',
  '3.1 Undefined',
  '3.2 FAB-250',
  '3.3 FAB-500',
  '3.4 Various KAB (guided FABs)',
  '4 Missile fire',
  '4.1 Undefined',
  '4.2 3M-54 Kalibr',
  '4.3 P-800 Oniks (3M55)',
  '4.4 Kh-22 / Kh- 32',
  '4.5 Kh-25',
  '4.6 Kh-31',
  '4.7 Kh-58',
  '4.8 Kh-101',
  '4.9 OTR-21 Tochka',
  '4.1 9K720 Iskander',
  '4.11 S-300 (SA-10 Grumble)',
  '4.12 Kh-59',
  '4.13 Kh-555',
  '4.14 S-400 Triumf (SA-21 Growler)',
  '5 Tank fire',
  '6 Vehicle Mounted Weapon',
  '7 Fire arms',
  '8 Explosive device',
  '8.1 Land mine or trip-wire',
  '8.2 Naval mine',
  '8.3 Unexploded artillery shell',
  '9 Abduction',
  '10 Torture',
  '11 UAV attack',
  '11.1 Loitering munition'
]
